### ISSUE TITLE
we should chat!

### ISSUE THREAD

**Issue by kirbyju** [bhklab/nbia-toolkit#108]
Hi there, I'm one of the project managers that runs TCIA and I also lead the development of NBIA.  It's very cool to see you've started up this repo.  I wanted to make sure you had seen https://github.com/kirbyju/TCIA_Notebooks and https://github.com/kirbyju/tcia_utils, and to see if you'd be interested to chat about potential ways we could collaborate.  

Best,
Justin

**Comment by jjjermiah** [comment]
Hi Justin, thanks for reaching out! I'd love to chat, feel free to shoot me an email at jermiahjoseph98@gmail.com and we can arrange something.
